name: Build RPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build RPK
        run: npm run build

      - name: Show output
        run: |
          find . -type f -name "*.rpk" -print
      - name: Upload RPK
        uses: actions/upload-artifact@v4
        with:
          name: calculator-rpk
          path: "**/*.rpk"
